#!/bin/sh
set -eu
umask 077
restore_root="$(python -m open_node.browser_restore_activate)"
restore_environment="${restore_root:+$restore_root/restore.env}"
if [ -n "$restore_environment" ] && [ -e "$restore_environment" ]; then
  [ -f "$restore_environment" ] && [ ! -L "$restore_environment" ] \
    && [ "$(stat -c '%u' "$restore_environment")" = "$(id -u)" ] \
    && [ "$(stat -c '%a' "$restore_environment")" = "600" ] \
    || { printf '%s\n' 'Open Node restore environment is unsafe.' >&2; exit 1; }
  set -a
  # Generated by the bounded restore service from fixed keys and validated key bytes.
  . "$restore_environment"
  set +a
fi
exec "$@"
